# Generated by Django 5.2.6 on 2025-09-16 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the faculty/department', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the faculty')),
                ('established_date', models.DateField(blank=True, help_text='Date when the faculty was established', null=True)),
                ('dean', models.CharField(blank=True, help_text='Name of the faculty dean', max_length=100)),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Student's first name", max_length=50)),
                ('last_name', models.CharField(help_text="Student's last name", max_length=50)),
                ('email', models.EmailField(help_text="Student's email address", max_length=254, unique=True)),
                ('student_id', models.CharField(help_text='Unique student identification number', max_length=20, unique=True)),
                ('enrollment_date', models.DateField(help_text='Date when the student enrolled')),
                ('graduation_year', models.IntegerField(blank=True, help_text='Expected graduation year', null=True)),
                ('date_of_birth', models.DateField(blank=True, help_text="Student's date of birth", null=True)),
                ('phone_number', models.CharField(blank=True, help_text="Student's phone number", max_length=15)),
                ('address', models.TextField(blank=True, help_text="Student's address")),
                ('is_active', models.BooleanField(default=True, help_text='Whether the student is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(help_text='Faculty the student belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='person.faculty')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
